apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongo-feedback.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mongo-feedback.labels" . | nindent 4 }}
  ports:
    - name: mongodb
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
