apiVersion: apps/v1
kind: Deployment
metadata:
  name: selmag-catalogue-service-deployment
  namespace: selmag
  labels:
    app: selmag-catalogue-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selmag-catalogue-service
  template:
    metadata:
      labels:
        app: selmag-catalogue-service
    spec:
      containers:
        - name: selmag-catalogue-service
          image: host.docker.internal:5000/selmag/catalogue-service:24.1.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: selmag-config
            - secretRef:
                name: selmag-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
#              value: "cloudconfig"
              value: "cloudconfig,observability"
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: selmag-config
                  key: CATALOGUE_SERVICE_PORT_INTERNAL
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
