apiVersion: v1
kind: Service
metadata:
  name: selmag-catalogue-service-svc
  namespace: selmag
spec:
  type: ClusterIP
  selector:
    app: selmag-catalogue-service
  ports:
    - name: http
      port: 8081
      targetPort: http
