image:
  repository: ghcr.io/gitueser/selmag/manager-app
  tag: "24.1.1"
  pullPolicy: IfNotPresent

replicaCount: 1

deployment:
  name: selmag-manager-app-deployment
  appLabel: selmag-manager-app

service:
  name: selmag-manager-app-svc
  type: ClusterIP
  port: 8087
  targetPortName: http

containerPort: 8087

env:
  springProfilesActive: "cloudconfig"
  serverPort: "8087"

probes:
  initialDelaySeconds: 60
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
  readinessPeriodSeconds: 10
  livenessPeriodSeconds: 20
  timeoutSeconds: 3
  readinessFailureThreshold: 12
  livenessFailureThreshold: 6
