#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: selmag-admin-server-ingress
#  namespace: selmag
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: admin.selm.ag.192.168.49.2.nip.io
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: selmag-admin-server-svc
#                port:
#                  name: http
