image:
  repository: host.docker.internal:5000/selmag/catalogue-service
  tag: "24.1.1"
  pullPolicy: Always

replicaCount: 3

deployment:
  name: selmag-catalogue-service-deployment
  appLabel: selmag-catalogue-service

service:
  name: selmag-catalogue-service-svc
  type: ClusterIP
  port: 8081
  targetPortName: http

containerPort: 8081

env:
  springProfilesActive: "cloudconfig"
  serverPort: "8081"

probes:
  initialDelaySeconds: 60
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
  readinessPeriodSeconds: 10
  livenessPeriodSeconds: 20
  timeoutSeconds: 3
  readinessFailureThreshold: 12
  livenessFailureThreshold: 6
