apiVersion: apps/v1
kind: Deployment
metadata:
  name: selmag-api-gateway-deployment
  namespace: selmag
  labels:
    app: selmag-api-gateway
spec:
  selector:
    matchLabels:
      app: selmag-api-gateway
  template:
    metadata:
      labels:
        app: selmag-api-gateway
    spec:
      containers:
        - name: selmag-api-gateway
          image: host.docker.internal:5000/selmag/api-gateway:24.1.1
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "cloudconfig"
            #              value: "cloudconfig,observability"
            - name: SERVER_PORT
              value: "8086"
          envFrom:
            - configMapRef:
                name: selmag-config
            - secretRef:
                name: selmag-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
