apiVersion: v1
kind: Service
metadata:
  name: selmag-eureka-server-svc
  namespace: selmag
spec:
  type: ClusterIP
  selector:
    app: selmag-eureka-server
  ports:
    - name: http
      port: 8761
      targetPort: http
