server:
  forward-headers-strategy: framework
spring:
  application:
    name: selmag-api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@config-server:8888