eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka-server}
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 60
  client:
    registryFetchIntervalSeconds: 20
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: ${KEYCLOAK_INTERNAL_ISSUER_URI:http://keycloak:8080/realms/selmag}
        registration:
          keycloak:
            client-id: ${EUREKA_SERVER_CLIENT_ID}
            client-secret: ${EUREKA_SERVER_CLIENT_SECRET}
            scope:
              - openid
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_INTERNAL_ISSUER_URI:http://keycloak:8080/realms/selmag}

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  tracing:
    enabled: false
