spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${MANAGER_APP_GATEWAY_CLIENT_ID}
            client-secret: ${MANAGER_APP_GATEWAY_CLIENT_SECRET}
          metrics:
            provider: keycloak
            client-id: ${MANAGER_APP_GATEWAY_CLIENT_ID}
            client-secret: ${MANAGER_APP_GATEWAY_CLIENT_SECRET}
          discovery:
            provider: keycloak
            client-id: ${MANAGER_APP_GATEWAY_CLIENT_ID}
            client-secret: ${MANAGER_APP_GATEWAY_CLIENT_SECRET}
