image:
  repository: grafana/loki
  tag: "2.9.4"
  pullPolicy: IfNotPresent

replicaCount: 1

deployment:
  name: selmag-loki-deployment
  appLabel: selmag-loki

args:
  - "-config.file=/etc/loki/local-config.yaml"

service:
  name: selmag-loki-svc
  type: ClusterIP
  port: 3100
  targetPortName: http

containerPort: 3100

storage:
  enabled: true
  volumeName: loki-data
  mountPath: /loki
  type: emptyDir

probes:
  readinessPath: /ready
  livenessPath: /ready
  initialDelaySeconds: 20
  readinessPeriodSeconds: 10
  livenessPeriodSeconds: 20
  timeoutSeconds: 3
  readinessFailureThreshold: 12
  livenessFailureThreshold: 6
