spring:
  boot:
    admin:
      client:
        enabled: false
  data:
    mongodb:
      uri: ${FEEDBACK_MONGODB_URI:mongodb://feedback-db:27017/feedback}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/selmag}
      client:
        registration:
          keycloak:
            client-id: ${FEEDBACK_SERVICE_CLIENT_ID}
            client-secret: ${FEEDBACK_SERVICE_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: ${FEEDBACK_SERVICE_CLIENT_ID}
            client-secret: ${FEEDBACK_SERVICE_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/selmag}
springdoc:
  swagger-ui:
    oauth:
      client-id: feedback-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
keycloak:
  uri: ${KEYCLOAK_PUBLIC_URI:http://keycloak:8080}

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  tracing:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 60
  client:
    registryFetchIntervalSeconds: 20
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE:http://eureka-server:8761/eureka/}
