image:
  repository: ghcr.io/gitueser/selmag/api-gateway
  tag: "sha-11c9212"
  pullPolicy: IfNotPresent

replicaCount: 1

deployment:
  name: selmag-api-gateway-deployment
  appLabel: selmag-api-gateway

service:
  name: selmag-api-gateway-svc
  type: ClusterIP
  port: 8086
  targetPortName: http

containerPort: 8086

env:
  springProfilesActive: "cloudconfig"
  serverPort: "8086"

probes:
  initialDelaySeconds: 60
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
  readinessPeriodSeconds: 10
  livenessPeriodSeconds: 20
  timeoutSeconds: 3
  readinessFailureThreshold: 12
  livenessFailureThreshold: 6

ingress:
  enabled: true
  name: selmag-api-gateway-ingress
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  hosts:
    - host: catalogue.api.selm.ag.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: Prefix
    - host: feedback.api.selm.ag.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: Prefix
    - host: manager.selm.ag.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: Prefix
    - host: customer.selm.ag.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: Prefix
