apiVersion: v1
kind: Service
metadata:
  name: selmag-feedback-service-svc
  namespace: selmag
spec:
  type: ClusterIP
  selector:
    app: selmag-feedback-service
  ports:
    - name: http
      port: 8084
      targetPort: http
