scrape_configs:
  - job_name: selmag-admin-service-job
    static_configs:
      - targets: ["http://admin-server:%{ADMIN_SERVER_PORT_INTERNAL}"]
        labels:
          application: selmag-admin-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: %{VICTORIA_METRICS_CLIENT_ID}
      client_secret: %{VICTORIA_METRICS_CLIENT_SECRET}
      token_url: %{KEYCLOAK_METRICS_TOKEN_URL}
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: selmag-api-gateway-job
    static_configs:
      - targets: ["http://api-gateway:%{API_GATEWAY_PORT_INTERNAL}"]
        labels:
          application: selmag-api-gateway
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: %{VICTORIA_METRICS_CLIENT_ID}
      client_secret: %{VICTORIA_METRICS_CLIENT_SECRET}
      token_url: %{KEYCLOAK_METRICS_TOKEN_URL}
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
#  - job_name: selmag-config-server-job
#    static_configs:
#      - targets: ["http://config-server:%{CONFIG_SERVER_PORT_INTERNAL}"]
#        labels:
#          application: selmag-config-server
#    metrics_path: /actuator/prometheus
#    oauth2:
#      client_id: %{VICTORIA_METRICS_CLIENT_ID}
#      client_secret: %{VICTORIA_METRICS_CLIENT_SECRET}
#      token_url: %{KEYCLOAK_METRICS_TOKEN_URL}
#      scopes:
#        - metrics
#      endpoint_params:
#        grant_type: client_credentials
#  - job_name: selmag-eureka-server-job
#    static_configs:
#      - targets: ["http://eureka-server:%{EUREKA_SERVER_PORT_INTERNAL}"]
#        labels:
#          application: selmag-eureka-server
#    metrics_path: /actuator/prometheus
#    oauth2:
#      client_id: %{VICTORIA_METRICS_CLIENT_ID}
#      client_secret: %{VICTORIA_METRICS_CLIENT_SECRET}
#      token_url: %{KEYCLOAK_METRICS_TOKEN_URL}
#      scopes:
#        - metrics
#      endpoint_params:
#        grant_type: client_credentials
  - job_name: selmag-catalogue-service-job
    static_configs:
      - targets: ["http://catalogue-service:%{CATALOGUE_SERVICE_PORT_INTERNAL}"]
        labels:
          application: selmag-catalogue-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: %{VICTORIA_METRICS_CLIENT_ID}
      client_secret: %{VICTORIA_METRICS_CLIENT_SECRET}
      token_url: %{KEYCLOAK_METRICS_TOKEN_URL}
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: selmag-feedback-service-job
    static_configs:
      - targets: ["http://feedback-service:%{FEEDBACK_SERVICE_PORT_INTERNAL}"]
        labels:
          application: selmag-feedback-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: %{VICTORIA_METRICS_CLIENT_ID}
      client_secret: %{VICTORIA_METRICS_CLIENT_SECRET}
      token_url: %{KEYCLOAK_METRICS_TOKEN_URL}
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: selmag-customer-app-job
    static_configs:
      - targets: ["http://customer-app:%{CUSTOMER_APP_PORT_INTERNAL}"]
        labels:
          application: selmag-customer-app
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: %{VICTORIA_METRICS_CLIENT_ID}
      client_secret: %{VICTORIA_METRICS_CLIENT_SECRET}
      token_url: %{KEYCLOAK_METRICS_TOKEN_URL}
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: selmag-manager-app-job
    static_configs:
      - targets: ["http://manager-app:%{MANAGER_APP_PORT_INTERNAL}"]
        labels:
          application: selmag-manager-app
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: %{VICTORIA_METRICS_CLIENT_ID}
      client_secret: %{VICTORIA_METRICS_CLIENT_SECRET}
      token_url: %{KEYCLOAK_METRICS_TOKEN_URL}
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
