apiVersion: apps/v1
kind: Deployment
metadata:
  name: selmag-customer-app-deployment
  namespace: selmag
  labels:
    app: selmag-customer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selmag-customer-app
  template:
    metadata:
      labels:
        app: selmag-customer-app
    spec:
      containers:
        - name: selmag-customer-app
          image: host.docker.internal:5000/selmag/customer-app:24.1.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "cloudconfig"
            # - name: SPRING_PROFILES_ACTIVE
            #   value: "cloudconfig,observability"
            - name: SERVER_PORT
              value: "8083"
          envFrom:
            - configMapRef:
                name: selmag-config
            - secretRef:
                name: selmag-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
