apiVersion: v1
kind: Service
metadata:
  name: selmag-customer-app-svc
  namespace: selmag
spec:
  type: ClusterIP
  selector:
    app: selmag-customer-app
  ports:
    - name: http
      port: 8083
      targetPort: 8083
