{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  labels:
    app: {{ .Values.statefulset.name }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.name }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: postgresql

          envFrom:
            - configMapRef:
                name: {{ .Values.env.configMapName }}
            - secretRef:
                name: {{ .Values.env.secretName }}

          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configMapName }}
                  key: {{ .Values.env.userKey }}
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configMapName }}
                  key: {{ .Values.env.dbKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.passwordKey }}

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvcName }}
{{- end }}
