image:
  repository: ghcr.io/gitueser/selmag/feedback-service
  tag: "sha-48c8a90"
  pullPolicy: IfNotPresent

replicaCount: 1

deployment:
  name: selmag-feedback-service-deployment
  appLabel: selmag-feedback-service

service:
  name: selmag-feedback-service-svc
  type: ClusterIP
  port: 8084
  targetPortName: http

containerPort: 8084

env:
  springProfilesActive: "cloudconfig"
  serverPort: "8084"

probes:
  initialDelaySeconds: 60
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
  readinessPeriodSeconds: 10
  livenessPeriodSeconds: 20
  timeoutSeconds: 3
  readinessFailureThreshold: 12
  livenessFailureThreshold: 6
