apiVersion: v2
name: selmag
description: Selmag umbrella chart (Spring Boot microservices + platform components) for local minikube/WSL2 environment.
type: application
version: 0.1.0
appVersion: "24.1.1"

dependencies:
  - name: keycloak
    version: 0.1.0
    repository: "file://charts/keycloak"
  - name: postgres-catalogue
    version: 0.1.0
    repository: "file://charts/postgres-catalogue"
  - name: mongo-feedback
    version: 0.1.0
    repository: "file://charts/mongo-feedback"
  - name: config-server
    version: 0.1.0
    repository: "file://charts/config-server"
  - name: eureka-server
    version: 0.1.0
    repository: "file://charts/eureka-server"
