apiVersion: v2
name: selmag
description: Selmag umbrella chart (Spring Boot microservices + platform components) for local minikube/WSL2 environment.
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: keycloak
    version: 0.1.0
    repository: "file://subcharts/platform/keycloak"
    condition: keycloak.enabled

  - name: postgres-catalogue
    version: 0.1.0
    repository: "file://subcharts/data/postgres-catalogue"
    condition: postgres-catalogue.enabled

  - name: mongo-feedback
    version: 0.1.0
    repository: "file://subcharts/data/mongo-feedback"
    condition: mongo-feedback.enabled

  - name: config-server
    version: 0.1.0
    repository: "file://subcharts/services/config-server"
    condition: config-server.enabled

  - name: eureka-server
    version: 0.1.0
    repository: "file://subcharts/services/eureka-server"
    condition: eureka-server.enabled

  - name: admin-server
    version: 0.1.0
    repository: "file://subcharts/services/admin-server"
    condition: admin-server.enabled

  - name: catalogue-service
    version: 0.1.0
    repository: "file://subcharts/services/catalogue-service"
    condition: catalogue-service.enabled

  - name: feedback-service
    version: 0.1.0
    repository: "file://subcharts/services/feedback-service"
    condition: feedback-service.enabled

  - name: customer-app
    version: 0.1.0
    repository: "file://subcharts/services/customer-app"
    condition: customer-app.enabled

  - name: manager-app
    version: 0.1.0
    repository: "file://subcharts/services/manager-app"
    condition: manager-app.enabled

  - name: api-gateway
    version: 0.1.0
    repository: "file://subcharts/services/api-gateway"
    condition: api-gateway.enabled

  - name: victoria-metrics
    version: 0.1.0
    repository: "file://subcharts/observability/victoria-metrics"
    condition: victoria-metrics.enabled

  - name: grafana
    version: 0.1.0
    repository: "file://subcharts/observability/grafana"
    condition: grafana.enabled

  - name: tempo
    version: 0.1.0
    repository: "file://subcharts/observability/tempo"
    condition: tempo.enabled

  - name: loki
    version: 0.1.0
    repository: "file://subcharts/observability/loki"
    condition: loki.enabled

  - name: promtail
    version: 0.1.0
    repository: "file://subcharts/observability/promtail"
    condition: promtail.enabled
