global:
#  namespace: selmag-helm

  # Локальный registry контейнер, доступный из pod'ов через host.docker.internal
  imageRegistry: host.docker.internal:5000

  # Общие имена ресурсов, как сейчас в k8s
  configMapName: selmag-config
  secretName: selmag-secret

  # Источники env-файлов в репозитории (мы будем поднимать их в ConfigMap/Secret)
  envFiles:
    config: k8s/shared/.env.config
    secret: k8s/shared/.env.secret

bootstrap:
  namespace:
    enabled: true

  configMap:
    enabled: true

  secret:
    enabled: true

admin-server:
  enabled: true

catalogue-service:
  enabled: true

feedback-service:
  enabled: true

customer-app:
  enabled: true

manager-app:
  enabled: true

api-gateway:
  enabled: true
