global:

  # Локальный registry контейнер, доступный из pod'ов через host.docker.internal
  imageRegistry: host.docker.internal:5000

  # Общие имена ресурсов, как сейчас в k8s
  configMapName: selmag-config
  secretName: selmag-secret

  envFiles:
    config: files/.env.config
    secret: files/.env.secret

bootstrap:
  configMap:
    enabled: true
  secret:
    enabled: true

keycloak:
  enabled: true

postgres-catalogue:
  enabled: true

mongo-feedback:
  enabled: true

config-server:
  enabled: true

eureka-server:
  enabled: true

admin-server:
  enabled: true

catalogue-service:
  enabled: true

feedback-service:
  enabled: true

customer-app:
  enabled: true

manager-app:
  enabled: true

api-gateway:
  enabled: true

victoria-metrics:
  enabled: false

grafana:
  enabled: false

tempo:
  enabled: false

loki:
  enabled: false

promtail:
  enabled: false
