{{- if .Values.realm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.realm.secretName }}
type: Opaque
data:
  {{ .Values.realm.fileName }}: {{ .Files.Get (printf "files/%s" .Values.realm.fileName) | b64enc }}
{{- end }}
