apiVersion: apps/v1
kind: Deployment
metadata:
  name: selmag-admin-server-deployment
  namespace: selmag
  labels:
    app: selmag-admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selmag-admin-server
  template:
    metadata:
      labels:
        app: selmag-admin-server
    spec:
      containers:
        - name: selmag-admin-server
          image: host.docker.internal:5000/selmag/admin-server:24.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
#              value: "cloudconfig"
              value: "cloudconfig,observability"
            - name: SERVER_PORT
              value: "8085"
          envFrom:
            - configMapRef:
                name: selmag-config
            - secretRef:
                name: selmag-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
