image:
  repository: ghcr.io/gitueser/selmag/customer-app
  tag: "sha-8468a3d"
  pullPolicy: IfNotPresent

replicaCount: 1

deployment:
  name: selmag-customer-app-deployment
  appLabel: selmag-customer-app

service:
  name: selmag-customer-app-svc
  type: ClusterIP
  port: 8083
  targetPortName: http

containerPort: 8083

env:
  springProfilesActive: "cloudconfig"
  serverPort: "8083"

probes:
  initialDelaySeconds: 60
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
  readinessPeriodSeconds: 10
  livenessPeriodSeconds: 20
  timeoutSeconds: 3
  readinessFailureThreshold: 12
  livenessFailureThreshold: 6
