apiVersion: apps/v1
kind: Deployment
metadata:
  name: selmag-victoria-metrics-deployment
  namespace: selmag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selmag-victoria-metrics
  template:
    metadata:
      labels:
        app: selmag-victoria-metrics
    spec:
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics:v1.93.12
          args: ["-promscrape.config=/etc/vm/promscrape.yaml"]
          ports:
            - name: http
              containerPort: 8428
          envFrom:
            - configMapRef:
                name: selmag-config
            - secretRef:
                name: selmag-secret
          volumeMounts:
            - name: vm-promscrape
              mountPath: /etc/vm
      volumes:
        - name: vm-promscrape
          configMap:
            name: selmag-vm-promscrape
