apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "grafana.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.deployment.appLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: {{ .Values.service.targetPortName }}
              containerPort: {{ .Values.containerPort }}

          volumeMounts:
            - name: grafana-datasources
              mountPath: {{ .Values.provisioning.datasources.mountPath }}
              readOnly: true

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: {{ .Values.service.targetPortName }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessPeriodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readinessFailureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: {{ .Values.service.targetPortName }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessPeriodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.livenessFailureThreshold }}

      volumes:
        - name: grafana-datasources
          configMap:
            name: {{ .Values.provisioning.datasources.configMapName }}
