apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "feedback-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "feedback-service.labels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.targetPortName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPortName }}
