enabled: true

image:
  repository: host.docker.internal:5000/selmag/customer-app
  tag: "24.1.1"
  pullPolicy: Always

replicaCount: 1

service:
  name: selmag-customer-app-svc
  port: 8083
  targetPortName: http

deployment:
  name: selmag-customer-app-deployment
  appLabel: selmag-customer-app

env:
  springProfilesActive: "cloudconfig"
#  springProfilesActive: "cloudconfig,observability"
  serverPort: "8083"

probes:
  initialDelaySeconds: 60
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
  readinessPeriodSeconds: 10
  livenessPeriodSeconds: 20
  timeoutSeconds: 3
  readinessFailureThreshold: 12
  livenessFailureThreshold: 6
