server:
  forward-headers-strategy: framework
selmag:
  services:
    catalogue:
      uri: ${CATALOGUE_SERVICE_URI:lb://selmag-catalogue-service}
    feedback:
      uri: ${FEEDBACK_SERVICE_URI:lb://selmag-feedback-service}
spring:
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_INTERNAL_ISSUER_URI:http://keycloak:8080/realms/selmag}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${CUSTOMER_APP_CLIENT_ID}
            client-secret: ${CUSTOMER_APP_CLIENT_SECRET}
            client-name: Selmag Keycloak
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: ${CUSTOMER_APP_CLIENT_ID}
            client-secret: ${CUSTOMER_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: ${CUSTOMER_APP_CLIENT_ID}
            client-secret: ${CUSTOMER_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_INTERNAL_ISSUER_URI:http://keycloak:8080/realms/selmag}
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  tracing:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 60
  client:
    registryFetchIntervalSeconds: 20
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE:http://eureka-server:8761/eureka/}
