image:
  repository: ghcr.io/gitueser/selmag/config-server
  tag: "sha-11c9212"
  pullPolicy: IfNotPresent

replicaCount: 1

deployment:
  name: selmag-config-server-deployment
  appLabel: selmag-config-server

service:
  name: selmag-config-server-svc
  type: ClusterIP
  port: 8888
  targetPortName: http

containerPort: 8888

env:
  springProfilesActive: "git"

envKeys:
  serverPortKey: CONFIG_SERVER_PORT_INTERNAL
  securityUsernameKey: CONFIG_SERVER_SECURITY_USERNAME
  gitLabelKey: CONFIG_GIT_LABEL
  securityPasswordKey: CONFIG_SERVER_SECURITY_PASSWORD

probes:
  initialDelaySeconds: 60
  readinessPeriodSeconds: 10
  livenessPeriodSeconds: 20
  timeoutSeconds: 3
  readinessFailureThreshold: 12
  livenessFailureThreshold: 6
  actuatorHealthPath: /actuator/health
