image:
  repository: ghcr.io/gitueser/selmag/admin-server
  tag: "sha-48c8a90"
  pullPolicy: IfNotPresent

replicaCount: 1

deployment:
  name: selmag-admin-server-deployment
  appLabel: selmag-admin-server

service:
  name: selmag-admin-server-svc
  type: ClusterIP
  port: 8085
  targetPortName: http

containerPort: 8085

env:
  springProfilesActive: "cloudconfig"
  serverPort: "8085"

probes:
  initialDelaySeconds: 60
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
  readinessPeriodSeconds: 10
  livenessPeriodSeconds: 20
  timeoutSeconds: 3
  readinessFailureThreshold: 12
  livenessFailureThreshold: 6
