{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "selmag.promtail.fullname" . }}
rules:
  # Promtail читает метаданные для автолейблинга (pod/namespace/node)
  - apiGroups: [""]
    resources: ["nodes", "pods", "services", "endpoints", "namespaces"]
    verbs: ["get", "list", "watch"]
{{- end -}}
