apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appLabel }}
    spec:
      containers:
        - name: selmag-catalogue-service
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}

          envFrom:
            - configMapRef:
                name: selmag-config
            - secretRef:
                name: selmag-secret

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfilesActive | quote }}
            - name: SERVER_PORT
              value: {{ .Values.env.serverPort | quote }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessPeriodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readinessFailureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessPeriodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.livenessFailureThreshold }}
