apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: selmag-admin-server
spec:
  type: ClusterIP
  selector:
    app: selmag-admin-server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
