spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_INTERNAL_ISSUER_URI:http://keycloak:8080/realms/selmag}

      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_INTERNAL_ISSUER_URI:http://keycloak:8080/realms/selmag}
            user-name-attribute: preferred_username

          # Browser-login:
          # - authorization-uri: PUBLIC (браузер открывает Keycloak снаружи)
          # - token/jwk/userinfo: через тот же hostname, что и KC_HOSTNAME_URL
          #   (в твоём k8s это внешний nip.io, и это сейчас принципиально важно, раз так работает)
          login:
            authorization-uri: ${KEYCLOAK_PUBLIC_URI:http://keycloak:8080}/realms/selmag/protocol/openid-connect/auth
            token-uri: ${KC_HOSTNAME_URL:http://keycloak:8080}/realms/selmag/protocol/openid-connect/token
            jwk-set-uri: ${KC_HOSTNAME_URL:http://keycloak:8080}/realms/selmag/protocol/openid-connect/certs
            user-info-uri: ${KC_HOSTNAME_URL:http://keycloak:8080}/realms/selmag/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: ${ADMIN_SERVICE_CLIENT_ID}
            client-secret: ${ADMIN_SERVICE_CLIENT_SECRET}

          # ВАЖНО: redirect-uri обязателен для authorization_code
          login:
            provider: login
            authorization-grant-type: authorization_code
            scope:
              - metrics
              - openid
            client-id: ${ADMIN_SERVICE_CLIENT_ID}
            client-secret: ${ADMIN_SERVICE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          discovery:
            provider: keycloak
            authorization-grant-type: client_credentials
            scope:
              - discovery
            client-id: ${ADMIN_SERVICE_CLIENT_ID}
            client-secret: ${ADMIN_SERVICE_CLIENT_SECRET}

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  tracing:
    enabled: false

eureka:
  instance:
    hostname: ${ADMIN_HOSTNAME:admin-server}
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 60
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE:http://eureka-server:8761/eureka/}
    registryFetchIntervalSeconds: 20
    register-with-eureka: false

server:
  forward-headers-strategy: framework
