apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "eureka-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eureka-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eureka-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.deployment.appLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: {{ .Values.service.targetPortName }}
              containerPort: {{ .Values.containerPort }}

          envFrom:
            - configMapRef:
                name: {{ $.Values.global.configMapName }}
            - secretRef:
                name: {{ $.Values.global.secretName }}

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfilesActive | quote }}

            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: {{ .Values.envKeys.serverPortKey }}

            - name: EUREKA_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: {{ .Values.envKeys.hostnameKey }}

            - name: CONFIG_SERVER_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: {{ .Values.envKeys.configServerUriKey }}

            - name: CONFIG_SERVER_SECURITY_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: {{ .Values.envKeys.configServerUsernameKey }}

            - name: CONFIG_SERVER_SECURITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secretName }}
                  key: {{ .Values.envKeys.configServerPasswordKey }}

            - name: EUREKA_SERVER_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: {{ .Values.envKeys.eurekaClientIdKey }}

            - name: EUREKA_SERVER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.secretName }}
                  key: {{ .Values.envKeys.eurekaClientSecretKey }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: {{ .Values.service.targetPortName }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessPeriodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readinessFailureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: {{ .Values.service.targetPortName }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessPeriodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.livenessFailureThreshold }}
