apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: selmag-eureka-server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
