apiVersion: v1
kind: Service
metadata:
  name: selmag-manager-app-svc
  namespace: selmag
spec:
  type: ClusterIP
  selector:
    app: selmag-manager-app
  ports:
    - name: http
      port: 8087
      targetPort: http
