apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
