spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CUSTOMER_APP_GATEWAY_CLIENT_ID}
            client-secret: ${CUSTOMER_APP_GATEWAY_CLIENT_SECRET}
          metrics:
            client-id: ${CUSTOMER_APP_GATEWAY_CLIENT_ID}
            client-secret: ${CUSTOMER_APP_GATEWAY_CLIENT_SECRET}
          discovery:
            client-id: ${CUSTOMER_APP_GATEWAY_CLIENT_ID}
            client-secret: ${CUSTOMER_APP_GATEWAY_CLIENT_SECRET}
